name: whixp
description: Streamline your XMPP messaging with a lightweight Dart-based XMPP client
version: 3.0.0
repository: https://github.com/vsevex/whixp
issue_tracker: https://github.com/vsevex/whixp/issues
topics: [xmpp, network, socket]

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dnsolve: ^2.0.0
  drift: ^2.30.1
  memoize: ^3.0.0
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.41
  synchronized: ^3.4.0
  unorm_dart: ^0.3.2
  xml: ^6.6.1

dev_dependencies:
  build_runner: ^2.10.5
  convert: ^3.1.2
  coverage: ^1.15.0
  drift_dev: ^2.30.1
  lint: ^2.3.0
  test: ^1.29.0

platforms:
  android:
  ios:
  macos:
  windows:
